//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Candy_shop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CandyShopEntities : DbContext
    {
        public CandyShopEntities()
            : base("name=CandyShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CashRegister> CashRegister { get; set; }
        public virtual DbSet<Manufacturers> Manufacturers { get; set; }
        public virtual DbSet<MoneyTransactions> MoneyTransactions { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ReceiptsOfProducts> ReceiptsOfProducts { get; set; }
        public virtual DbSet<SalesOfProducts> SalesOfProducts { get; set; }
        public virtual DbSet<Shifts> Shifts { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Warehouses> Warehouses { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
        public virtual DbSet<WritesOffOfProducts> WritesOffOfProducts { get; set; }
    }
}
