//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Candy_shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoneyTransactions
    {
        public int MoneyTransactionID { get; set; }
        public int CashRegisterID_FK { get; set; }
        public int WorkerID_FK { get; set; }
        public decimal Deposits { get; set; }
        public decimal Withdrawals { get; set; }
        public System.DateTime DateOfOperation { get; set; }
    
        public virtual CashRegister CashRegister { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
