//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Candy_shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.ReceiptsOfProducts = new HashSet<ReceiptsOfProducts>();
            this.SalesOfProducts = new HashSet<SalesOfProducts>();
            this.Warehouses = new HashSet<Warehouses>();
            this.WritesOffOfProducts = new HashSet<WritesOffOfProducts>();
        }
    
        public int ProductID { get; set; }
        public int ManufacturerID_FK { get; set; }
        public string NameOfProduct { get; set; }
        public decimal Price { get; set; }
        public decimal PurchasePrice { get; set; }
        public int ExpirationDate { get; set; }
    
        public virtual Manufacturers Manufacturers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptsOfProducts> ReceiptsOfProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOfProducts> SalesOfProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Warehouses> Warehouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WritesOffOfProducts> WritesOffOfProducts { get; set; }
    }
}
